name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - release
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@v1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: latest

      - uses: swift-actions/setup-swift@v2

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .build/reports/
