# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "release" ]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    - name: Build
      run: xcodebuild -workspace StepUp.xcworkspace -scheme "StepUp" -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' build
    - name: Run tests
      run: xcodebuild test -workspace StepUp.xcworkspace -scheme "StepUp" -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4'
